
CREATE TABLE IF NOT EXISTS Users (
	id BIGINT(20) NOT NULL AUTO_INCREMENT,
	address VARCHAR(255) NULL DEFAULT NULL,
	date_of_birth DATETIME NULL DEFAULT NULL,
	first_name VARCHAR(255) NULL DEFAULT NULL,
	last_name VARCHAR(255) NULL DEFAULT NULL,
	password VARCHAR(255) NULL DEFAULT NULL,
	phone_number VARCHAR(255) NULL DEFAULT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS Accounts (
	id BIGINT(20) NOT NULL,
	balance DOUBLE NOT NULL,
	user_id BIGINT(20) NULL DEFAULT NULL,
	PRIMARY KEY (id),
	CONSTRAINT FK_Accounts_Users FOREIGN KEY (user_id) REFERENCES Users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS Roles (
	id BIGINT(20) NOT NULL,
	default_role BIT(1) NOT NULL,
	name VARCHAR(255) NULL DEFAULT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS Users_Roles (
	user_id BIGINT(20) NOT NULL,
	role_id BIGINT(20) NOT NULL,
	CONSTRAINT FK_Roles_Users FOREIGN KEY (user_id) REFERENCES Users (id),
	CONSTRAINT FK_Users_Roles FOREIGN KEY (role_id) REFERENCES Roles (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS Transactions (
	id BIGINT(20) NOT NULL AUTO_INCREMENT,
	account_number_from BIGINT(20) NOT NULL,
	account_number_to BIGINT(20) NOT NULL,
	amount DOUBLE NOT NULL,
	balance_before_transfer_from DOUBLE NOT NULL,
	balance_before_transfer_to DOUBLE NOT NULL,
	date DATETIME NULL DEFAULT NULL,
	description_from VARCHAR(255) NULL DEFAULT NULL,
	description_to VARCHAR(255) NULL DEFAULT NULL,
	user_id BIGINT(20) NOT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB AUTO_INCREMENT=16 DEFAULT CHARSET=utf8;
